### ISSUE TITLE
Not working when the yml file contains a "pip" term.

### ISSUE THREAD

**Issue by Leojc** [MarcoGorelli/madforhooks#14]
Without the "pip" term, it works like a charm!
However, when the yml file contains a "pip" term in it, it raises an error.

Example:
```yaml
# environment.yml

name: xx
channels:
- defaults
dependencies:
- python=3.8
- pip:
    - transformers
```

raise an error:
``` TypeError: '<' not supported between instances of 'CommentedMap' and 'str' ```
